### ISSUE TITLE
Multiplayer Morph Mod Bug

### ISSUE THREAD

**Issue by ghost** [Budschie/BudschieMorphMod#71]
Hello, I've been having a lot of problems with the morph mod on LAN games with my friend. It started when I killed a mob, morphed into it, and got disconnected because of a timeout error. After this I joined back and all of my morphs were gone. When I killed another mob to get it's morph I couldn't morph into that mob, but the mob I killed previously, and now the mobs in my morph inventory are all random. I cannot get the whole list to show either. Another problem is that sometimes my friend cannot see when I morph, as in I see a turtle but he sees me. I'm willing to send anything, I'm just not sure how.
Thanks a million!

**Comment by Budschie** [comment]
I think this is sorta fixed now due to commit 7da4632c1dceb47c18e9d1d2f36836fc197466a7.

**Comment by nop1984** [comment]
@Budschie seems not fixed. I use 1.18 with 2.0.1 mod version (client and server)
Each time I rejoin the world my morph menu is empty. But when I kill mob it does not drop the soul assuming like I have it (but menu is empty, one big red X only item). When I kill mob I had not before and it drops soul, then sometimes (not each time) all my previous mobs are shown in menu too after picking soul.
For server owner all works OK, but for peers not.

**Comment by kordisgod** [comment]
> @Budschie seems not fixed. I use 1.18 with 2.0.1 mod version (client and server) Each time I rejoin the world my morph menu is empty. But when I kill mob it does not drop the soul assuming like I have it (but menu is empty, one big red X only item). When I kill mob I had not before and it drops soul, then sometimes (not each time) all my previous mobs are shown in menu too after picking soul. For server owner all works OK, but for peers not.

did you ever find a fix? i have the same issue
